import Nav from "@/components/Nav/Nav";
import { main } from "./font";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="hu">
      <body className={main.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
